name: Build and deploy Node.js app to Azure Web App - VekanGCC

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and test
        run: |
          npm install
          npm test -- --passWithNoTests

      - name: Zip app contents (flattened structure)
        run: |
          cd ..
          zip -r release.zip VekanGCCBackend/* VekanGCCBackend/.* -x "VekanGCCBackend/.git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ../release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_962420EB7B07474DA1DCCCA069A4A462 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_28505FD3867E4D99A5893A61F33BBF54 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E1FF0E6EDD9042349C9DB003FDA2F0D7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VekanGCC'
          slot-name: 'Production'
          package: .
